# Generated by Django 2.1.7 on 2019-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190407_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpageid',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
